// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

var TableNames = struct {
	Conversations    string
	IndexedDocuments string
	IndexingDLQ      string
	Messages         string
	Reports          string
}{
	Conversations:    "conversations",
	IndexedDocuments: "indexed_documents",
	IndexingDLQ:      "indexing_dlq",
	Messages:         "messages",
	Reports:          "reports",
}
