// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

var ViewNames = struct {
	IndexingErrorSummary   string
	IndexingHealthCheck    string
	IndexingStatsByBatch   string
	IndexingStatsByProject string
}{
	IndexingErrorSummary:   "indexing_error_summary",
	IndexingHealthCheck:    "indexing_health_check",
	IndexingStatsByBatch:   "indexing_stats_by_batch",
	IndexingStatsByProject: "indexing_stats_by_project",
}
