// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

var TableNames = struct {
	Conversations     string
	IndexedDocuments  string
	IndexingDLQ       string
	MaestroSessions   string
	Messages          string
	NotebookCampaigns string
	NotebookChatJobs  string
	NotebookSources   string
	Reports           string
}{
	Conversations:     "conversations",
	IndexedDocuments:  "indexed_documents",
	IndexingDLQ:       "indexing_dlq",
	MaestroSessions:   "maestro_sessions",
	Messages:          "messages",
	NotebookCampaigns: "notebook_campaigns",
	NotebookChatJobs:  "notebook_chat_jobs",
	NotebookSources:   "notebook_sources",
	Reports:           "reports",
}
