// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// IndexingErrorSummary is an object representing the database table.
type IndexingErrorSummary struct {
	ErrorType       null.String       `boil:"error_type" json:"error_type,omitempty" toml:"error_type" yaml:"error_type,omitempty"`
	ErrorCount      null.Int64        `boil:"error_count" json:"error_count,omitempty" toml:"error_count" yaml:"error_count,omitempty"`
	UniqueRecords   null.Int64        `boil:"unique_records" json:"unique_records,omitempty" toml:"unique_records" yaml:"unique_records,omitempty"`
	AffectedBatches null.Int64        `boil:"affected_batches" json:"affected_batches,omitempty" toml:"affected_batches" yaml:"affected_batches,omitempty"`
	ResolvedCount   null.Int64        `boil:"resolved_count" json:"resolved_count,omitempty" toml:"resolved_count" yaml:"resolved_count,omitempty"`
	UnresolvedCount null.Int64        `boil:"unresolved_count" json:"unresolved_count,omitempty" toml:"unresolved_count" yaml:"unresolved_count,omitempty"`
	AvgRetryCount   types.NullDecimal `boil:"avg_retry_count" json:"avg_retry_count,omitempty" toml:"avg_retry_count" yaml:"avg_retry_count,omitempty"`
	MaxRetryCount   null.Int          `boil:"max_retry_count" json:"max_retry_count,omitempty" toml:"max_retry_count" yaml:"max_retry_count,omitempty"`
	FirstErrorAt    null.Time         `boil:"first_error_at" json:"first_error_at,omitempty" toml:"first_error_at" yaml:"first_error_at,omitempty"`
	LastErrorAt     null.Time         `boil:"last_error_at" json:"last_error_at,omitempty" toml:"last_error_at" yaml:"last_error_at,omitempty"`
	ErrorsLast24H   null.Int64        `boil:"errors_last_24h" json:"errors_last_24h,omitempty" toml:"errors_last_24h" yaml:"errors_last_24h,omitempty"`
}

var IndexingErrorSummaryColumns = struct {
	ErrorType       string
	ErrorCount      string
	UniqueRecords   string
	AffectedBatches string
	ResolvedCount   string
	UnresolvedCount string
	AvgRetryCount   string
	MaxRetryCount   string
	FirstErrorAt    string
	LastErrorAt     string
	ErrorsLast24H   string
}{
	ErrorType:       "error_type",
	ErrorCount:      "error_count",
	UniqueRecords:   "unique_records",
	AffectedBatches: "affected_batches",
	ResolvedCount:   "resolved_count",
	UnresolvedCount: "unresolved_count",
	AvgRetryCount:   "avg_retry_count",
	MaxRetryCount:   "max_retry_count",
	FirstErrorAt:    "first_error_at",
	LastErrorAt:     "last_error_at",
	ErrorsLast24H:   "errors_last_24h",
}

var IndexingErrorSummaryTableColumns = struct {
	ErrorType       string
	ErrorCount      string
	UniqueRecords   string
	AffectedBatches string
	ResolvedCount   string
	UnresolvedCount string
	AvgRetryCount   string
	MaxRetryCount   string
	FirstErrorAt    string
	LastErrorAt     string
	ErrorsLast24H   string
}{
	ErrorType:       "indexing_error_summary.error_type",
	ErrorCount:      "indexing_error_summary.error_count",
	UniqueRecords:   "indexing_error_summary.unique_records",
	AffectedBatches: "indexing_error_summary.affected_batches",
	ResolvedCount:   "indexing_error_summary.resolved_count",
	UnresolvedCount: "indexing_error_summary.unresolved_count",
	AvgRetryCount:   "indexing_error_summary.avg_retry_count",
	MaxRetryCount:   "indexing_error_summary.max_retry_count",
	FirstErrorAt:    "indexing_error_summary.first_error_at",
	LastErrorAt:     "indexing_error_summary.last_error_at",
	ErrorsLast24H:   "indexing_error_summary.errors_last_24h",
}

// Generated where

type whereHelpertypes_NullDecimal struct{ field string }

func (w whereHelpertypes_NullDecimal) EQ(x types.NullDecimal) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpertypes_NullDecimal) NEQ(x types.NullDecimal) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpertypes_NullDecimal) LT(x types.NullDecimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_NullDecimal) LTE(x types.NullDecimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_NullDecimal) GT(x types.NullDecimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_NullDecimal) GTE(x types.NullDecimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpertypes_NullDecimal) IsNull() qm.QueryMod { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpertypes_NullDecimal) IsNotNull() qm.QueryMod {
	return qmhelper.WhereIsNotNull(w.field)
}

var IndexingErrorSummaryWhere = struct {
	ErrorType       whereHelpernull_String
	ErrorCount      whereHelpernull_Int64
	UniqueRecords   whereHelpernull_Int64
	AffectedBatches whereHelpernull_Int64
	ResolvedCount   whereHelpernull_Int64
	UnresolvedCount whereHelpernull_Int64
	AvgRetryCount   whereHelpertypes_NullDecimal
	MaxRetryCount   whereHelpernull_Int
	FirstErrorAt    whereHelpernull_Time
	LastErrorAt     whereHelpernull_Time
	ErrorsLast24H   whereHelpernull_Int64
}{
	ErrorType:       whereHelpernull_String{field: "\"schema_knowledge\".\"indexing_error_summary\".\"error_type\""},
	ErrorCount:      whereHelpernull_Int64{field: "\"schema_knowledge\".\"indexing_error_summary\".\"error_count\""},
	UniqueRecords:   whereHelpernull_Int64{field: "\"schema_knowledge\".\"indexing_error_summary\".\"unique_records\""},
	AffectedBatches: whereHelpernull_Int64{field: "\"schema_knowledge\".\"indexing_error_summary\".\"affected_batches\""},
	ResolvedCount:   whereHelpernull_Int64{field: "\"schema_knowledge\".\"indexing_error_summary\".\"resolved_count\""},
	UnresolvedCount: whereHelpernull_Int64{field: "\"schema_knowledge\".\"indexing_error_summary\".\"unresolved_count\""},
	AvgRetryCount:   whereHelpertypes_NullDecimal{field: "\"schema_knowledge\".\"indexing_error_summary\".\"avg_retry_count\""},
	MaxRetryCount:   whereHelpernull_Int{field: "\"schema_knowledge\".\"indexing_error_summary\".\"max_retry_count\""},
	FirstErrorAt:    whereHelpernull_Time{field: "\"schema_knowledge\".\"indexing_error_summary\".\"first_error_at\""},
	LastErrorAt:     whereHelpernull_Time{field: "\"schema_knowledge\".\"indexing_error_summary\".\"last_error_at\""},
	ErrorsLast24H:   whereHelpernull_Int64{field: "\"schema_knowledge\".\"indexing_error_summary\".\"errors_last_24h\""},
}

var (
	indexingErrorSummaryAllColumns            = []string{"error_type", "error_count", "unique_records", "affected_batches", "resolved_count", "unresolved_count", "avg_retry_count", "max_retry_count", "first_error_at", "last_error_at", "errors_last_24h"}
	indexingErrorSummaryColumnsWithoutDefault = []string{}
	indexingErrorSummaryColumnsWithDefault    = []string{"error_type", "error_count", "unique_records", "affected_batches", "resolved_count", "unresolved_count", "avg_retry_count", "max_retry_count", "first_error_at", "last_error_at", "errors_last_24h"}
	indexingErrorSummaryPrimaryKeyColumns     = []string{}
	indexingErrorSummaryGeneratedColumns      = []string{}
)

type (
	// IndexingErrorSummarySlice is an alias for a slice of pointers to IndexingErrorSummary.
	// This should almost always be used instead of []IndexingErrorSummary.
	IndexingErrorSummarySlice []*IndexingErrorSummary
	// IndexingErrorSummaryHook is the signature for custom IndexingErrorSummary hook methods
	IndexingErrorSummaryHook func(context.Context, boil.ContextExecutor, *IndexingErrorSummary) error

	indexingErrorSummaryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	indexingErrorSummaryType           = reflect.TypeOf(&IndexingErrorSummary{})
	indexingErrorSummaryMapping        = queries.MakeStructMapping(indexingErrorSummaryType)
	indexingErrorSummaryInsertCacheMut sync.RWMutex
	indexingErrorSummaryInsertCache    = make(map[string]insertCache)
	indexingErrorSummaryUpdateCacheMut sync.RWMutex
	indexingErrorSummaryUpdateCache    = make(map[string]updateCache)
	indexingErrorSummaryUpsertCacheMut sync.RWMutex
	indexingErrorSummaryUpsertCache    = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
	// These are used in some views
	_ = fmt.Sprintln("")
	_ = reflect.Int
	_ = strings.Builder{}
	_ = sync.Mutex{}
	_ = strmangle.Plural("")
	_ = strconv.IntSize
)

var indexingErrorSummaryAfterSelectMu sync.Mutex
var indexingErrorSummaryAfterSelectHooks []IndexingErrorSummaryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *IndexingErrorSummary) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range indexingErrorSummaryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddIndexingErrorSummaryHook registers your hook function for all future operations.
func AddIndexingErrorSummaryHook(hookPoint boil.HookPoint, indexingErrorSummaryHook IndexingErrorSummaryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		indexingErrorSummaryAfterSelectMu.Lock()
		indexingErrorSummaryAfterSelectHooks = append(indexingErrorSummaryAfterSelectHooks, indexingErrorSummaryHook)
		indexingErrorSummaryAfterSelectMu.Unlock()
	}
}

// One returns a single indexingErrorSummary record from the query.
func (q indexingErrorSummaryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*IndexingErrorSummary, error) {
	o := &IndexingErrorSummary{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for indexing_error_summary")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all IndexingErrorSummary records from the query.
func (q indexingErrorSummaryQuery) All(ctx context.Context, exec boil.ContextExecutor) (IndexingErrorSummarySlice, error) {
	var o []*IndexingErrorSummary

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to IndexingErrorSummary slice")
	}

	if len(indexingErrorSummaryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all IndexingErrorSummary records in the query.
func (q indexingErrorSummaryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count indexing_error_summary rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q indexingErrorSummaryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if indexing_error_summary exists")
	}

	return count > 0, nil
}

// IndexingErrorSummaries retrieves all the records using an executor.
func IndexingErrorSummaries(mods ...qm.QueryMod) indexingErrorSummaryQuery {
	mods = append(mods, qm.From("\"schema_knowledge\".\"indexing_error_summary\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"schema_knowledge\".\"indexing_error_summary\".*"})
	}

	return indexingErrorSummaryQuery{q}
}
