// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// IndexingHealthCheck is an object representing the database table.
type IndexingHealthCheck struct {
	TotalIndexed     null.Int64        `boil:"total_indexed" json:"total_indexed,omitempty" toml:"total_indexed" yaml:"total_indexed,omitempty"`
	TotalFailed      null.Int64        `boil:"total_failed" json:"total_failed,omitempty" toml:"total_failed" yaml:"total_failed,omitempty"`
	TotalPending     null.Int64        `boil:"total_pending" json:"total_pending,omitempty" toml:"total_pending" yaml:"total_pending,omitempty"`
	RecordsLastHour  null.Int64        `boil:"records_last_hour" json:"records_last_hour,omitempty" toml:"records_last_hour" yaml:"records_last_hour,omitempty"`
	IndexedLastHour  null.Int64        `boil:"indexed_last_hour" json:"indexed_last_hour,omitempty" toml:"indexed_last_hour" yaml:"indexed_last_hour,omitempty"`
	StalePending     null.Int64        `boil:"stale_pending" json:"stale_pending,omitempty" toml:"stale_pending" yaml:"stale_pending,omitempty"`
	UnresolvedErrors null.Int64        `boil:"unresolved_errors" json:"unresolved_errors,omitempty" toml:"unresolved_errors" yaml:"unresolved_errors,omitempty"`
	AvgTimeMSRecent  types.NullDecimal `boil:"avg_time_ms_recent" json:"avg_time_ms_recent,omitempty" toml:"avg_time_ms_recent" yaml:"avg_time_ms_recent,omitempty"`
	LastIndexedAt    null.Time         `boil:"last_indexed_at" json:"last_indexed_at,omitempty" toml:"last_indexed_at" yaml:"last_indexed_at,omitempty"`
	CheckedAt        null.Time         `boil:"checked_at" json:"checked_at,omitempty" toml:"checked_at" yaml:"checked_at,omitempty"`
}

var IndexingHealthCheckColumns = struct {
	TotalIndexed     string
	TotalFailed      string
	TotalPending     string
	RecordsLastHour  string
	IndexedLastHour  string
	StalePending     string
	UnresolvedErrors string
	AvgTimeMSRecent  string
	LastIndexedAt    string
	CheckedAt        string
}{
	TotalIndexed:     "total_indexed",
	TotalFailed:      "total_failed",
	TotalPending:     "total_pending",
	RecordsLastHour:  "records_last_hour",
	IndexedLastHour:  "indexed_last_hour",
	StalePending:     "stale_pending",
	UnresolvedErrors: "unresolved_errors",
	AvgTimeMSRecent:  "avg_time_ms_recent",
	LastIndexedAt:    "last_indexed_at",
	CheckedAt:        "checked_at",
}

var IndexingHealthCheckTableColumns = struct {
	TotalIndexed     string
	TotalFailed      string
	TotalPending     string
	RecordsLastHour  string
	IndexedLastHour  string
	StalePending     string
	UnresolvedErrors string
	AvgTimeMSRecent  string
	LastIndexedAt    string
	CheckedAt        string
}{
	TotalIndexed:     "indexing_health_check.total_indexed",
	TotalFailed:      "indexing_health_check.total_failed",
	TotalPending:     "indexing_health_check.total_pending",
	RecordsLastHour:  "indexing_health_check.records_last_hour",
	IndexedLastHour:  "indexing_health_check.indexed_last_hour",
	StalePending:     "indexing_health_check.stale_pending",
	UnresolvedErrors: "indexing_health_check.unresolved_errors",
	AvgTimeMSRecent:  "indexing_health_check.avg_time_ms_recent",
	LastIndexedAt:    "indexing_health_check.last_indexed_at",
	CheckedAt:        "indexing_health_check.checked_at",
}

// Generated where

var IndexingHealthCheckWhere = struct {
	TotalIndexed     whereHelpernull_Int64
	TotalFailed      whereHelpernull_Int64
	TotalPending     whereHelpernull_Int64
	RecordsLastHour  whereHelpernull_Int64
	IndexedLastHour  whereHelpernull_Int64
	StalePending     whereHelpernull_Int64
	UnresolvedErrors whereHelpernull_Int64
	AvgTimeMSRecent  whereHelpertypes_NullDecimal
	LastIndexedAt    whereHelpernull_Time
	CheckedAt        whereHelpernull_Time
}{
	TotalIndexed:     whereHelpernull_Int64{field: "\"schema_knowledge\".\"indexing_health_check\".\"total_indexed\""},
	TotalFailed:      whereHelpernull_Int64{field: "\"schema_knowledge\".\"indexing_health_check\".\"total_failed\""},
	TotalPending:     whereHelpernull_Int64{field: "\"schema_knowledge\".\"indexing_health_check\".\"total_pending\""},
	RecordsLastHour:  whereHelpernull_Int64{field: "\"schema_knowledge\".\"indexing_health_check\".\"records_last_hour\""},
	IndexedLastHour:  whereHelpernull_Int64{field: "\"schema_knowledge\".\"indexing_health_check\".\"indexed_last_hour\""},
	StalePending:     whereHelpernull_Int64{field: "\"schema_knowledge\".\"indexing_health_check\".\"stale_pending\""},
	UnresolvedErrors: whereHelpernull_Int64{field: "\"schema_knowledge\".\"indexing_health_check\".\"unresolved_errors\""},
	AvgTimeMSRecent:  whereHelpertypes_NullDecimal{field: "\"schema_knowledge\".\"indexing_health_check\".\"avg_time_ms_recent\""},
	LastIndexedAt:    whereHelpernull_Time{field: "\"schema_knowledge\".\"indexing_health_check\".\"last_indexed_at\""},
	CheckedAt:        whereHelpernull_Time{field: "\"schema_knowledge\".\"indexing_health_check\".\"checked_at\""},
}

var (
	indexingHealthCheckAllColumns            = []string{"total_indexed", "total_failed", "total_pending", "records_last_hour", "indexed_last_hour", "stale_pending", "unresolved_errors", "avg_time_ms_recent", "last_indexed_at", "checked_at"}
	indexingHealthCheckColumnsWithoutDefault = []string{}
	indexingHealthCheckColumnsWithDefault    = []string{"total_indexed", "total_failed", "total_pending", "records_last_hour", "indexed_last_hour", "stale_pending", "unresolved_errors", "avg_time_ms_recent", "last_indexed_at", "checked_at"}
	indexingHealthCheckPrimaryKeyColumns     = []string{}
	indexingHealthCheckGeneratedColumns      = []string{}
)

type (
	// IndexingHealthCheckSlice is an alias for a slice of pointers to IndexingHealthCheck.
	// This should almost always be used instead of []IndexingHealthCheck.
	IndexingHealthCheckSlice []*IndexingHealthCheck
	// IndexingHealthCheckHook is the signature for custom IndexingHealthCheck hook methods
	IndexingHealthCheckHook func(context.Context, boil.ContextExecutor, *IndexingHealthCheck) error

	indexingHealthCheckQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	indexingHealthCheckType           = reflect.TypeOf(&IndexingHealthCheck{})
	indexingHealthCheckMapping        = queries.MakeStructMapping(indexingHealthCheckType)
	indexingHealthCheckInsertCacheMut sync.RWMutex
	indexingHealthCheckInsertCache    = make(map[string]insertCache)
	indexingHealthCheckUpdateCacheMut sync.RWMutex
	indexingHealthCheckUpdateCache    = make(map[string]updateCache)
	indexingHealthCheckUpsertCacheMut sync.RWMutex
	indexingHealthCheckUpsertCache    = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
	// These are used in some views
	_ = fmt.Sprintln("")
	_ = reflect.Int
	_ = strings.Builder{}
	_ = sync.Mutex{}
	_ = strmangle.Plural("")
	_ = strconv.IntSize
)

var indexingHealthCheckAfterSelectMu sync.Mutex
var indexingHealthCheckAfterSelectHooks []IndexingHealthCheckHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *IndexingHealthCheck) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range indexingHealthCheckAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddIndexingHealthCheckHook registers your hook function for all future operations.
func AddIndexingHealthCheckHook(hookPoint boil.HookPoint, indexingHealthCheckHook IndexingHealthCheckHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		indexingHealthCheckAfterSelectMu.Lock()
		indexingHealthCheckAfterSelectHooks = append(indexingHealthCheckAfterSelectHooks, indexingHealthCheckHook)
		indexingHealthCheckAfterSelectMu.Unlock()
	}
}

// One returns a single indexingHealthCheck record from the query.
func (q indexingHealthCheckQuery) One(ctx context.Context, exec boil.ContextExecutor) (*IndexingHealthCheck, error) {
	o := &IndexingHealthCheck{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for indexing_health_check")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all IndexingHealthCheck records from the query.
func (q indexingHealthCheckQuery) All(ctx context.Context, exec boil.ContextExecutor) (IndexingHealthCheckSlice, error) {
	var o []*IndexingHealthCheck

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to IndexingHealthCheck slice")
	}

	if len(indexingHealthCheckAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all IndexingHealthCheck records in the query.
func (q indexingHealthCheckQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count indexing_health_check rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q indexingHealthCheckQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if indexing_health_check exists")
	}

	return count > 0, nil
}

// IndexingHealthChecks retrieves all the records using an executor.
func IndexingHealthChecks(mods ...qm.QueryMod) indexingHealthCheckQuery {
	mods = append(mods, qm.From("\"schema_knowledge\".\"indexing_health_check\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"schema_knowledge\".\"indexing_health_check\".*"})
	}

	return indexingHealthCheckQuery{q}
}
