// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// IndexingDLQ is an object representing the database table.
type IndexingDLQ struct {
	ID          string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	AnalyticsID string      `boil:"analytics_id" json:"analytics_id" toml:"analytics_id" yaml:"analytics_id"`
	BatchID     null.String `boil:"batch_id" json:"batch_id,omitempty" toml:"batch_id" yaml:"batch_id,omitempty"`
	// JSONB containing the original AnalyticsPost record for replay after the bug is fixed
	RawPayload   types.JSON `boil:"raw_payload" json:"raw_payload" toml:"raw_payload" yaml:"raw_payload"`
	ErrorMessage string     `boil:"error_message" json:"error_message" toml:"error_message" yaml:"error_message"`
	// Type of error: PARSE_ERROR (JSON parse), EMBEDDING_ERROR (embedding generation), QDRANT_ERROR (upsert failure), DB_ERROR (database error)
	ErrorType  string   `boil:"error_type" json:"error_type" toml:"error_type" yaml:"error_type"`
	RetryCount null.Int `boil:"retry_count" json:"retry_count,omitempty" toml:"retry_count" yaml:"retry_count,omitempty"`
	MaxRetries null.Int `boil:"max_retries" json:"max_retries,omitempty" toml:"max_retries" yaml:"max_retries,omitempty"`
	// true = Admin has reviewed and handled this record (fixed, replayed, or decided to skip)
	Resolved  null.Bool `boil:"resolved" json:"resolved,omitempty" toml:"resolved" yaml:"resolved,omitempty"`
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *indexingDLQR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L indexingDLQL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var IndexingDLQColumns = struct {
	ID           string
	AnalyticsID  string
	BatchID      string
	RawPayload   string
	ErrorMessage string
	ErrorType    string
	RetryCount   string
	MaxRetries   string
	Resolved     string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	AnalyticsID:  "analytics_id",
	BatchID:      "batch_id",
	RawPayload:   "raw_payload",
	ErrorMessage: "error_message",
	ErrorType:    "error_type",
	RetryCount:   "retry_count",
	MaxRetries:   "max_retries",
	Resolved:     "resolved",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

var IndexingDLQTableColumns = struct {
	ID           string
	AnalyticsID  string
	BatchID      string
	RawPayload   string
	ErrorMessage string
	ErrorType    string
	RetryCount   string
	MaxRetries   string
	Resolved     string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "indexing_dlq.id",
	AnalyticsID:  "indexing_dlq.analytics_id",
	BatchID:      "indexing_dlq.batch_id",
	RawPayload:   "indexing_dlq.raw_payload",
	ErrorMessage: "indexing_dlq.error_message",
	ErrorType:    "indexing_dlq.error_type",
	RetryCount:   "indexing_dlq.retry_count",
	MaxRetries:   "indexing_dlq.max_retries",
	Resolved:     "indexing_dlq.resolved",
	CreatedAt:    "indexing_dlq.created_at",
	UpdatedAt:    "indexing_dlq.updated_at",
}

// Generated where

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpernull_Bool struct{ field string }

func (w whereHelpernull_Bool) EQ(x null.Bool) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Bool) NEQ(x null.Bool) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Bool) LT(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Bool) LTE(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Bool) GT(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Bool) GTE(x null.Bool) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Bool) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Bool) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var IndexingDLQWhere = struct {
	ID           whereHelperstring
	AnalyticsID  whereHelperstring
	BatchID      whereHelpernull_String
	RawPayload   whereHelpertypes_JSON
	ErrorMessage whereHelperstring
	ErrorType    whereHelperstring
	RetryCount   whereHelpernull_Int
	MaxRetries   whereHelpernull_Int
	Resolved     whereHelpernull_Bool
	CreatedAt    whereHelpernull_Time
	UpdatedAt    whereHelpernull_Time
}{
	ID:           whereHelperstring{field: "\"schema_knowledge\".\"indexing_dlq\".\"id\""},
	AnalyticsID:  whereHelperstring{field: "\"schema_knowledge\".\"indexing_dlq\".\"analytics_id\""},
	BatchID:      whereHelpernull_String{field: "\"schema_knowledge\".\"indexing_dlq\".\"batch_id\""},
	RawPayload:   whereHelpertypes_JSON{field: "\"schema_knowledge\".\"indexing_dlq\".\"raw_payload\""},
	ErrorMessage: whereHelperstring{field: "\"schema_knowledge\".\"indexing_dlq\".\"error_message\""},
	ErrorType:    whereHelperstring{field: "\"schema_knowledge\".\"indexing_dlq\".\"error_type\""},
	RetryCount:   whereHelpernull_Int{field: "\"schema_knowledge\".\"indexing_dlq\".\"retry_count\""},
	MaxRetries:   whereHelpernull_Int{field: "\"schema_knowledge\".\"indexing_dlq\".\"max_retries\""},
	Resolved:     whereHelpernull_Bool{field: "\"schema_knowledge\".\"indexing_dlq\".\"resolved\""},
	CreatedAt:    whereHelpernull_Time{field: "\"schema_knowledge\".\"indexing_dlq\".\"created_at\""},
	UpdatedAt:    whereHelpernull_Time{field: "\"schema_knowledge\".\"indexing_dlq\".\"updated_at\""},
}

// IndexingDLQRels is where relationship names are stored.
var IndexingDLQRels = struct {
}{}

// indexingDLQR is where relationships are stored.
type indexingDLQR struct {
}

// NewStruct creates a new relationship struct
func (*indexingDLQR) NewStruct() *indexingDLQR {
	return &indexingDLQR{}
}

// indexingDLQL is where Load methods for each relationship are stored.
type indexingDLQL struct{}

var (
	indexingDLQAllColumns            = []string{"id", "analytics_id", "batch_id", "raw_payload", "error_message", "error_type", "retry_count", "max_retries", "resolved", "created_at", "updated_at"}
	indexingDLQColumnsWithoutDefault = []string{"analytics_id", "raw_payload", "error_message", "error_type"}
	indexingDLQColumnsWithDefault    = []string{"id", "batch_id", "retry_count", "max_retries", "resolved", "created_at", "updated_at"}
	indexingDLQPrimaryKeyColumns     = []string{"id"}
	indexingDLQGeneratedColumns      = []string{}
)

type (
	// IndexingDLQSlice is an alias for a slice of pointers to IndexingDLQ.
	// This should almost always be used instead of []IndexingDLQ.
	IndexingDLQSlice []*IndexingDLQ
	// IndexingDLQHook is the signature for custom IndexingDLQ hook methods
	IndexingDLQHook func(context.Context, boil.ContextExecutor, *IndexingDLQ) error

	indexingDLQQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	indexingDLQType                 = reflect.TypeOf(&IndexingDLQ{})
	indexingDLQMapping              = queries.MakeStructMapping(indexingDLQType)
	indexingDLQPrimaryKeyMapping, _ = queries.BindMapping(indexingDLQType, indexingDLQMapping, indexingDLQPrimaryKeyColumns)
	indexingDLQInsertCacheMut       sync.RWMutex
	indexingDLQInsertCache          = make(map[string]insertCache)
	indexingDLQUpdateCacheMut       sync.RWMutex
	indexingDLQUpdateCache          = make(map[string]updateCache)
	indexingDLQUpsertCacheMut       sync.RWMutex
	indexingDLQUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var indexingDLQAfterSelectMu sync.Mutex
var indexingDLQAfterSelectHooks []IndexingDLQHook

var indexingDLQBeforeInsertMu sync.Mutex
var indexingDLQBeforeInsertHooks []IndexingDLQHook
var indexingDLQAfterInsertMu sync.Mutex
var indexingDLQAfterInsertHooks []IndexingDLQHook

var indexingDLQBeforeUpdateMu sync.Mutex
var indexingDLQBeforeUpdateHooks []IndexingDLQHook
var indexingDLQAfterUpdateMu sync.Mutex
var indexingDLQAfterUpdateHooks []IndexingDLQHook

var indexingDLQBeforeDeleteMu sync.Mutex
var indexingDLQBeforeDeleteHooks []IndexingDLQHook
var indexingDLQAfterDeleteMu sync.Mutex
var indexingDLQAfterDeleteHooks []IndexingDLQHook

var indexingDLQBeforeUpsertMu sync.Mutex
var indexingDLQBeforeUpsertHooks []IndexingDLQHook
var indexingDLQAfterUpsertMu sync.Mutex
var indexingDLQAfterUpsertHooks []IndexingDLQHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *IndexingDLQ) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range indexingDLQAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *IndexingDLQ) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range indexingDLQBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *IndexingDLQ) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range indexingDLQAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *IndexingDLQ) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range indexingDLQBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *IndexingDLQ) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range indexingDLQAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *IndexingDLQ) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range indexingDLQBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *IndexingDLQ) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range indexingDLQAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *IndexingDLQ) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range indexingDLQBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *IndexingDLQ) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range indexingDLQAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddIndexingDLQHook registers your hook function for all future operations.
func AddIndexingDLQHook(hookPoint boil.HookPoint, indexingDLQHook IndexingDLQHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		indexingDLQAfterSelectMu.Lock()
		indexingDLQAfterSelectHooks = append(indexingDLQAfterSelectHooks, indexingDLQHook)
		indexingDLQAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		indexingDLQBeforeInsertMu.Lock()
		indexingDLQBeforeInsertHooks = append(indexingDLQBeforeInsertHooks, indexingDLQHook)
		indexingDLQBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		indexingDLQAfterInsertMu.Lock()
		indexingDLQAfterInsertHooks = append(indexingDLQAfterInsertHooks, indexingDLQHook)
		indexingDLQAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		indexingDLQBeforeUpdateMu.Lock()
		indexingDLQBeforeUpdateHooks = append(indexingDLQBeforeUpdateHooks, indexingDLQHook)
		indexingDLQBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		indexingDLQAfterUpdateMu.Lock()
		indexingDLQAfterUpdateHooks = append(indexingDLQAfterUpdateHooks, indexingDLQHook)
		indexingDLQAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		indexingDLQBeforeDeleteMu.Lock()
		indexingDLQBeforeDeleteHooks = append(indexingDLQBeforeDeleteHooks, indexingDLQHook)
		indexingDLQBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		indexingDLQAfterDeleteMu.Lock()
		indexingDLQAfterDeleteHooks = append(indexingDLQAfterDeleteHooks, indexingDLQHook)
		indexingDLQAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		indexingDLQBeforeUpsertMu.Lock()
		indexingDLQBeforeUpsertHooks = append(indexingDLQBeforeUpsertHooks, indexingDLQHook)
		indexingDLQBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		indexingDLQAfterUpsertMu.Lock()
		indexingDLQAfterUpsertHooks = append(indexingDLQAfterUpsertHooks, indexingDLQHook)
		indexingDLQAfterUpsertMu.Unlock()
	}
}

// One returns a single indexingDLQ record from the query.
func (q indexingDLQQuery) One(ctx context.Context, exec boil.ContextExecutor) (*IndexingDLQ, error) {
	o := &IndexingDLQ{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for indexing_dlq")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all IndexingDLQ records from the query.
func (q indexingDLQQuery) All(ctx context.Context, exec boil.ContextExecutor) (IndexingDLQSlice, error) {
	var o []*IndexingDLQ

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to IndexingDLQ slice")
	}

	if len(indexingDLQAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all IndexingDLQ records in the query.
func (q indexingDLQQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count indexing_dlq rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q indexingDLQQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if indexing_dlq exists")
	}

	return count > 0, nil
}

// IndexingDLQS retrieves all the records using an executor.
func IndexingDLQS(mods ...qm.QueryMod) indexingDLQQuery {
	mods = append(mods, qm.From("\"schema_knowledge\".\"indexing_dlq\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"schema_knowledge\".\"indexing_dlq\".*"})
	}

	return indexingDLQQuery{q}
}

// FindIndexingDLQ retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindIndexingDLQ(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*IndexingDLQ, error) {
	indexingDLQObj := &IndexingDLQ{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"schema_knowledge\".\"indexing_dlq\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, indexingDLQObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from indexing_dlq")
	}

	if err = indexingDLQObj.doAfterSelectHooks(ctx, exec); err != nil {
		return indexingDLQObj, err
	}

	return indexingDLQObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *IndexingDLQ) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no indexing_dlq provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(indexingDLQColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	indexingDLQInsertCacheMut.RLock()
	cache, cached := indexingDLQInsertCache[key]
	indexingDLQInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			indexingDLQAllColumns,
			indexingDLQColumnsWithDefault,
			indexingDLQColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(indexingDLQType, indexingDLQMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(indexingDLQType, indexingDLQMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"schema_knowledge\".\"indexing_dlq\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"schema_knowledge\".\"indexing_dlq\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into indexing_dlq")
	}

	if !cached {
		indexingDLQInsertCacheMut.Lock()
		indexingDLQInsertCache[key] = cache
		indexingDLQInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the IndexingDLQ.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *IndexingDLQ) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	indexingDLQUpdateCacheMut.RLock()
	cache, cached := indexingDLQUpdateCache[key]
	indexingDLQUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			indexingDLQAllColumns,
			indexingDLQPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update indexing_dlq, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"schema_knowledge\".\"indexing_dlq\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, indexingDLQPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(indexingDLQType, indexingDLQMapping, append(wl, indexingDLQPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update indexing_dlq row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for indexing_dlq")
	}

	if !cached {
		indexingDLQUpdateCacheMut.Lock()
		indexingDLQUpdateCache[key] = cache
		indexingDLQUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q indexingDLQQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for indexing_dlq")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for indexing_dlq")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o IndexingDLQSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), indexingDLQPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"schema_knowledge\".\"indexing_dlq\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, indexingDLQPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in indexingDLQ slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all indexingDLQ")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *IndexingDLQ) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no indexing_dlq provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(indexingDLQColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	indexingDLQUpsertCacheMut.RLock()
	cache, cached := indexingDLQUpsertCache[key]
	indexingDLQUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			indexingDLQAllColumns,
			indexingDLQColumnsWithDefault,
			indexingDLQColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			indexingDLQAllColumns,
			indexingDLQPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert indexing_dlq, could not build update column list")
		}

		ret := strmangle.SetComplement(indexingDLQAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(indexingDLQPrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert indexing_dlq, could not build conflict column list")
			}

			conflict = make([]string, len(indexingDLQPrimaryKeyColumns))
			copy(conflict, indexingDLQPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"schema_knowledge\".\"indexing_dlq\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(indexingDLQType, indexingDLQMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(indexingDLQType, indexingDLQMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert indexing_dlq")
	}

	if !cached {
		indexingDLQUpsertCacheMut.Lock()
		indexingDLQUpsertCache[key] = cache
		indexingDLQUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single IndexingDLQ record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *IndexingDLQ) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no IndexingDLQ provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), indexingDLQPrimaryKeyMapping)
	sql := "DELETE FROM \"schema_knowledge\".\"indexing_dlq\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from indexing_dlq")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for indexing_dlq")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q indexingDLQQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no indexingDLQQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from indexing_dlq")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for indexing_dlq")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o IndexingDLQSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(indexingDLQBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), indexingDLQPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"schema_knowledge\".\"indexing_dlq\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, indexingDLQPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from indexingDLQ slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for indexing_dlq")
	}

	if len(indexingDLQAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *IndexingDLQ) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindIndexingDLQ(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *IndexingDLQSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := IndexingDLQSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), indexingDLQPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"schema_knowledge\".\"indexing_dlq\".* FROM \"schema_knowledge\".\"indexing_dlq\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, indexingDLQPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in IndexingDLQSlice")
	}

	*o = slice

	return nil
}

// IndexingDLQExists checks if the IndexingDLQ row exists.
func IndexingDLQExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"schema_knowledge\".\"indexing_dlq\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if indexing_dlq exists")
	}

	return exists, nil
}

// Exists checks if the IndexingDLQ row exists.
func (o *IndexingDLQ) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return IndexingDLQExists(ctx, exec, o.ID)
}
