// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// MaestroSession is an object representing the database table.
type MaestroSession struct {
	ID            string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	SessionID     string      `boil:"session_id" json:"session_id" toml:"session_id" yaml:"session_id"`
	Status        string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	PodName       null.String `boil:"pod_name" json:"pod_name,omitempty" toml:"pod_name" yaml:"pod_name,omitempty"`
	CreatedAt     null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	LastUsedAt    null.Time   `boil:"last_used_at" json:"last_used_at,omitempty" toml:"last_used_at" yaml:"last_used_at,omitempty"`
	LastCheckedAt null.Time   `boil:"last_checked_at" json:"last_checked_at,omitempty" toml:"last_checked_at" yaml:"last_checked_at,omitempty"`

	R *maestroSessionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L maestroSessionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MaestroSessionColumns = struct {
	ID            string
	SessionID     string
	Status        string
	PodName       string
	CreatedAt     string
	LastUsedAt    string
	LastCheckedAt string
}{
	ID:            "id",
	SessionID:     "session_id",
	Status:        "status",
	PodName:       "pod_name",
	CreatedAt:     "created_at",
	LastUsedAt:    "last_used_at",
	LastCheckedAt: "last_checked_at",
}

var MaestroSessionTableColumns = struct {
	ID            string
	SessionID     string
	Status        string
	PodName       string
	CreatedAt     string
	LastUsedAt    string
	LastCheckedAt string
}{
	ID:            "maestro_sessions.id",
	SessionID:     "maestro_sessions.session_id",
	Status:        "maestro_sessions.status",
	PodName:       "maestro_sessions.pod_name",
	CreatedAt:     "maestro_sessions.created_at",
	LastUsedAt:    "maestro_sessions.last_used_at",
	LastCheckedAt: "maestro_sessions.last_checked_at",
}

// Generated where

var MaestroSessionWhere = struct {
	ID            whereHelperstring
	SessionID     whereHelperstring
	Status        whereHelperstring
	PodName       whereHelpernull_String
	CreatedAt     whereHelpernull_Time
	LastUsedAt    whereHelpernull_Time
	LastCheckedAt whereHelpernull_Time
}{
	ID:            whereHelperstring{field: "\"knowledge\".\"maestro_sessions\".\"id\""},
	SessionID:     whereHelperstring{field: "\"knowledge\".\"maestro_sessions\".\"session_id\""},
	Status:        whereHelperstring{field: "\"knowledge\".\"maestro_sessions\".\"status\""},
	PodName:       whereHelpernull_String{field: "\"knowledge\".\"maestro_sessions\".\"pod_name\""},
	CreatedAt:     whereHelpernull_Time{field: "\"knowledge\".\"maestro_sessions\".\"created_at\""},
	LastUsedAt:    whereHelpernull_Time{field: "\"knowledge\".\"maestro_sessions\".\"last_used_at\""},
	LastCheckedAt: whereHelpernull_Time{field: "\"knowledge\".\"maestro_sessions\".\"last_checked_at\""},
}

// MaestroSessionRels is where relationship names are stored.
var MaestroSessionRels = struct {
}{}

// maestroSessionR is where relationships are stored.
type maestroSessionR struct {
}

// NewStruct creates a new relationship struct
func (*maestroSessionR) NewStruct() *maestroSessionR {
	return &maestroSessionR{}
}

// maestroSessionL is where Load methods for each relationship are stored.
type maestroSessionL struct{}

var (
	maestroSessionAllColumns            = []string{"id", "session_id", "status", "pod_name", "created_at", "last_used_at", "last_checked_at"}
	maestroSessionColumnsWithoutDefault = []string{"session_id"}
	maestroSessionColumnsWithDefault    = []string{"id", "status", "pod_name", "created_at", "last_used_at", "last_checked_at"}
	maestroSessionPrimaryKeyColumns     = []string{"id"}
	maestroSessionGeneratedColumns      = []string{}
)

type (
	// MaestroSessionSlice is an alias for a slice of pointers to MaestroSession.
	// This should almost always be used instead of []MaestroSession.
	MaestroSessionSlice []*MaestroSession
	// MaestroSessionHook is the signature for custom MaestroSession hook methods
	MaestroSessionHook func(context.Context, boil.ContextExecutor, *MaestroSession) error

	maestroSessionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	maestroSessionType                 = reflect.TypeOf(&MaestroSession{})
	maestroSessionMapping              = queries.MakeStructMapping(maestroSessionType)
	maestroSessionPrimaryKeyMapping, _ = queries.BindMapping(maestroSessionType, maestroSessionMapping, maestroSessionPrimaryKeyColumns)
	maestroSessionInsertCacheMut       sync.RWMutex
	maestroSessionInsertCache          = make(map[string]insertCache)
	maestroSessionUpdateCacheMut       sync.RWMutex
	maestroSessionUpdateCache          = make(map[string]updateCache)
	maestroSessionUpsertCacheMut       sync.RWMutex
	maestroSessionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var maestroSessionAfterSelectMu sync.Mutex
var maestroSessionAfterSelectHooks []MaestroSessionHook

var maestroSessionBeforeInsertMu sync.Mutex
var maestroSessionBeforeInsertHooks []MaestroSessionHook
var maestroSessionAfterInsertMu sync.Mutex
var maestroSessionAfterInsertHooks []MaestroSessionHook

var maestroSessionBeforeUpdateMu sync.Mutex
var maestroSessionBeforeUpdateHooks []MaestroSessionHook
var maestroSessionAfterUpdateMu sync.Mutex
var maestroSessionAfterUpdateHooks []MaestroSessionHook

var maestroSessionBeforeDeleteMu sync.Mutex
var maestroSessionBeforeDeleteHooks []MaestroSessionHook
var maestroSessionAfterDeleteMu sync.Mutex
var maestroSessionAfterDeleteHooks []MaestroSessionHook

var maestroSessionBeforeUpsertMu sync.Mutex
var maestroSessionBeforeUpsertHooks []MaestroSessionHook
var maestroSessionAfterUpsertMu sync.Mutex
var maestroSessionAfterUpsertHooks []MaestroSessionHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MaestroSession) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range maestroSessionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MaestroSession) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range maestroSessionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MaestroSession) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range maestroSessionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MaestroSession) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range maestroSessionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MaestroSession) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range maestroSessionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MaestroSession) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range maestroSessionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MaestroSession) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range maestroSessionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MaestroSession) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range maestroSessionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MaestroSession) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range maestroSessionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMaestroSessionHook registers your hook function for all future operations.
func AddMaestroSessionHook(hookPoint boil.HookPoint, maestroSessionHook MaestroSessionHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		maestroSessionAfterSelectMu.Lock()
		maestroSessionAfterSelectHooks = append(maestroSessionAfterSelectHooks, maestroSessionHook)
		maestroSessionAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		maestroSessionBeforeInsertMu.Lock()
		maestroSessionBeforeInsertHooks = append(maestroSessionBeforeInsertHooks, maestroSessionHook)
		maestroSessionBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		maestroSessionAfterInsertMu.Lock()
		maestroSessionAfterInsertHooks = append(maestroSessionAfterInsertHooks, maestroSessionHook)
		maestroSessionAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		maestroSessionBeforeUpdateMu.Lock()
		maestroSessionBeforeUpdateHooks = append(maestroSessionBeforeUpdateHooks, maestroSessionHook)
		maestroSessionBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		maestroSessionAfterUpdateMu.Lock()
		maestroSessionAfterUpdateHooks = append(maestroSessionAfterUpdateHooks, maestroSessionHook)
		maestroSessionAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		maestroSessionBeforeDeleteMu.Lock()
		maestroSessionBeforeDeleteHooks = append(maestroSessionBeforeDeleteHooks, maestroSessionHook)
		maestroSessionBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		maestroSessionAfterDeleteMu.Lock()
		maestroSessionAfterDeleteHooks = append(maestroSessionAfterDeleteHooks, maestroSessionHook)
		maestroSessionAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		maestroSessionBeforeUpsertMu.Lock()
		maestroSessionBeforeUpsertHooks = append(maestroSessionBeforeUpsertHooks, maestroSessionHook)
		maestroSessionBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		maestroSessionAfterUpsertMu.Lock()
		maestroSessionAfterUpsertHooks = append(maestroSessionAfterUpsertHooks, maestroSessionHook)
		maestroSessionAfterUpsertMu.Unlock()
	}
}

// One returns a single maestroSession record from the query.
func (q maestroSessionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MaestroSession, error) {
	o := &MaestroSession{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for maestro_sessions")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MaestroSession records from the query.
func (q maestroSessionQuery) All(ctx context.Context, exec boil.ContextExecutor) (MaestroSessionSlice, error) {
	var o []*MaestroSession

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to MaestroSession slice")
	}

	if len(maestroSessionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MaestroSession records in the query.
func (q maestroSessionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count maestro_sessions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q maestroSessionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if maestro_sessions exists")
	}

	return count > 0, nil
}

// MaestroSessions retrieves all the records using an executor.
func MaestroSessions(mods ...qm.QueryMod) maestroSessionQuery {
	mods = append(mods, qm.From("\"knowledge\".\"maestro_sessions\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"knowledge\".\"maestro_sessions\".*"})
	}

	return maestroSessionQuery{q}
}

// FindMaestroSession retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMaestroSession(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*MaestroSession, error) {
	maestroSessionObj := &MaestroSession{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"knowledge\".\"maestro_sessions\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, maestroSessionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from maestro_sessions")
	}

	if err = maestroSessionObj.doAfterSelectHooks(ctx, exec); err != nil {
		return maestroSessionObj, err
	}

	return maestroSessionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MaestroSession) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no maestro_sessions provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(maestroSessionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	maestroSessionInsertCacheMut.RLock()
	cache, cached := maestroSessionInsertCache[key]
	maestroSessionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			maestroSessionAllColumns,
			maestroSessionColumnsWithDefault,
			maestroSessionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(maestroSessionType, maestroSessionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(maestroSessionType, maestroSessionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"knowledge\".\"maestro_sessions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"knowledge\".\"maestro_sessions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into maestro_sessions")
	}

	if !cached {
		maestroSessionInsertCacheMut.Lock()
		maestroSessionInsertCache[key] = cache
		maestroSessionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MaestroSession.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MaestroSession) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	maestroSessionUpdateCacheMut.RLock()
	cache, cached := maestroSessionUpdateCache[key]
	maestroSessionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			maestroSessionAllColumns,
			maestroSessionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update maestro_sessions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"knowledge\".\"maestro_sessions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, maestroSessionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(maestroSessionType, maestroSessionMapping, append(wl, maestroSessionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update maestro_sessions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for maestro_sessions")
	}

	if !cached {
		maestroSessionUpdateCacheMut.Lock()
		maestroSessionUpdateCache[key] = cache
		maestroSessionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q maestroSessionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for maestro_sessions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for maestro_sessions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MaestroSessionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), maestroSessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"knowledge\".\"maestro_sessions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, maestroSessionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in maestroSession slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all maestroSession")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MaestroSession) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no maestro_sessions provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(maestroSessionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	maestroSessionUpsertCacheMut.RLock()
	cache, cached := maestroSessionUpsertCache[key]
	maestroSessionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			maestroSessionAllColumns,
			maestroSessionColumnsWithDefault,
			maestroSessionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			maestroSessionAllColumns,
			maestroSessionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert maestro_sessions, could not build update column list")
		}

		ret := strmangle.SetComplement(maestroSessionAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(maestroSessionPrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert maestro_sessions, could not build conflict column list")
			}

			conflict = make([]string, len(maestroSessionPrimaryKeyColumns))
			copy(conflict, maestroSessionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"knowledge\".\"maestro_sessions\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(maestroSessionType, maestroSessionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(maestroSessionType, maestroSessionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert maestro_sessions")
	}

	if !cached {
		maestroSessionUpsertCacheMut.Lock()
		maestroSessionUpsertCache[key] = cache
		maestroSessionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MaestroSession record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MaestroSession) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no MaestroSession provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), maestroSessionPrimaryKeyMapping)
	sql := "DELETE FROM \"knowledge\".\"maestro_sessions\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from maestro_sessions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for maestro_sessions")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q maestroSessionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no maestroSessionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from maestro_sessions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for maestro_sessions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MaestroSessionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(maestroSessionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), maestroSessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"knowledge\".\"maestro_sessions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, maestroSessionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from maestroSession slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for maestro_sessions")
	}

	if len(maestroSessionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MaestroSession) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMaestroSession(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MaestroSessionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MaestroSessionSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), maestroSessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"knowledge\".\"maestro_sessions\".* FROM \"knowledge\".\"maestro_sessions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, maestroSessionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in MaestroSessionSlice")
	}

	*o = slice

	return nil
}

// MaestroSessionExists checks if the MaestroSession row exists.
func MaestroSessionExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"knowledge\".\"maestro_sessions\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if maestro_sessions exists")
	}

	return exists, nil
}

// Exists checks if the MaestroSession row exists.
func (o *MaestroSession) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return MaestroSessionExists(ctx, exec, o.ID)
}
