// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// NotebookChatJob is an object representing the database table.
type NotebookChatJob struct {
	ID             string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	ConversationID string      `boil:"conversation_id" json:"conversation_id" toml:"conversation_id" yaml:"conversation_id"`
	CampaignID     string      `boil:"campaign_id" json:"campaign_id" toml:"campaign_id" yaml:"campaign_id"`
	UserMessage    string      `boil:"user_message" json:"user_message" toml:"user_message" yaml:"user_message"`
	MaestroJobID   null.String `boil:"maestro_job_id" json:"maestro_job_id,omitempty" toml:"maestro_job_id" yaml:"maestro_job_id,omitempty"`
	Status         string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	NotebookAnswer null.String `boil:"notebook_answer" json:"notebook_answer,omitempty" toml:"notebook_answer" yaml:"notebook_answer,omitempty"`
	FallbackUsed   bool        `boil:"fallback_used" json:"fallback_used" toml:"fallback_used" yaml:"fallback_used"`
	CreatedAt      null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	CompletedAt    null.Time   `boil:"completed_at" json:"completed_at,omitempty" toml:"completed_at" yaml:"completed_at,omitempty"`
	ExpiresAt      null.Time   `boil:"expires_at" json:"expires_at,omitempty" toml:"expires_at" yaml:"expires_at,omitempty"`

	R *notebookChatJobR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L notebookChatJobL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var NotebookChatJobColumns = struct {
	ID             string
	ConversationID string
	CampaignID     string
	UserMessage    string
	MaestroJobID   string
	Status         string
	NotebookAnswer string
	FallbackUsed   string
	CreatedAt      string
	CompletedAt    string
	ExpiresAt      string
}{
	ID:             "id",
	ConversationID: "conversation_id",
	CampaignID:     "campaign_id",
	UserMessage:    "user_message",
	MaestroJobID:   "maestro_job_id",
	Status:         "status",
	NotebookAnswer: "notebook_answer",
	FallbackUsed:   "fallback_used",
	CreatedAt:      "created_at",
	CompletedAt:    "completed_at",
	ExpiresAt:      "expires_at",
}

var NotebookChatJobTableColumns = struct {
	ID             string
	ConversationID string
	CampaignID     string
	UserMessage    string
	MaestroJobID   string
	Status         string
	NotebookAnswer string
	FallbackUsed   string
	CreatedAt      string
	CompletedAt    string
	ExpiresAt      string
}{
	ID:             "notebook_chat_jobs.id",
	ConversationID: "notebook_chat_jobs.conversation_id",
	CampaignID:     "notebook_chat_jobs.campaign_id",
	UserMessage:    "notebook_chat_jobs.user_message",
	MaestroJobID:   "notebook_chat_jobs.maestro_job_id",
	Status:         "notebook_chat_jobs.status",
	NotebookAnswer: "notebook_chat_jobs.notebook_answer",
	FallbackUsed:   "notebook_chat_jobs.fallback_used",
	CreatedAt:      "notebook_chat_jobs.created_at",
	CompletedAt:    "notebook_chat_jobs.completed_at",
	ExpiresAt:      "notebook_chat_jobs.expires_at",
}

// Generated where

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var NotebookChatJobWhere = struct {
	ID             whereHelperstring
	ConversationID whereHelperstring
	CampaignID     whereHelperstring
	UserMessage    whereHelperstring
	MaestroJobID   whereHelpernull_String
	Status         whereHelperstring
	NotebookAnswer whereHelpernull_String
	FallbackUsed   whereHelperbool
	CreatedAt      whereHelpernull_Time
	CompletedAt    whereHelpernull_Time
	ExpiresAt      whereHelpernull_Time
}{
	ID:             whereHelperstring{field: "\"knowledge\".\"notebook_chat_jobs\".\"id\""},
	ConversationID: whereHelperstring{field: "\"knowledge\".\"notebook_chat_jobs\".\"conversation_id\""},
	CampaignID:     whereHelperstring{field: "\"knowledge\".\"notebook_chat_jobs\".\"campaign_id\""},
	UserMessage:    whereHelperstring{field: "\"knowledge\".\"notebook_chat_jobs\".\"user_message\""},
	MaestroJobID:   whereHelpernull_String{field: "\"knowledge\".\"notebook_chat_jobs\".\"maestro_job_id\""},
	Status:         whereHelperstring{field: "\"knowledge\".\"notebook_chat_jobs\".\"status\""},
	NotebookAnswer: whereHelpernull_String{field: "\"knowledge\".\"notebook_chat_jobs\".\"notebook_answer\""},
	FallbackUsed:   whereHelperbool{field: "\"knowledge\".\"notebook_chat_jobs\".\"fallback_used\""},
	CreatedAt:      whereHelpernull_Time{field: "\"knowledge\".\"notebook_chat_jobs\".\"created_at\""},
	CompletedAt:    whereHelpernull_Time{field: "\"knowledge\".\"notebook_chat_jobs\".\"completed_at\""},
	ExpiresAt:      whereHelpernull_Time{field: "\"knowledge\".\"notebook_chat_jobs\".\"expires_at\""},
}

// NotebookChatJobRels is where relationship names are stored.
var NotebookChatJobRels = struct {
}{}

// notebookChatJobR is where relationships are stored.
type notebookChatJobR struct {
}

// NewStruct creates a new relationship struct
func (*notebookChatJobR) NewStruct() *notebookChatJobR {
	return &notebookChatJobR{}
}

// notebookChatJobL is where Load methods for each relationship are stored.
type notebookChatJobL struct{}

var (
	notebookChatJobAllColumns            = []string{"id", "conversation_id", "campaign_id", "user_message", "maestro_job_id", "status", "notebook_answer", "fallback_used", "created_at", "completed_at", "expires_at"}
	notebookChatJobColumnsWithoutDefault = []string{"conversation_id", "campaign_id", "user_message"}
	notebookChatJobColumnsWithDefault    = []string{"id", "maestro_job_id", "status", "notebook_answer", "fallback_used", "created_at", "completed_at", "expires_at"}
	notebookChatJobPrimaryKeyColumns     = []string{"id"}
	notebookChatJobGeneratedColumns      = []string{}
)

type (
	// NotebookChatJobSlice is an alias for a slice of pointers to NotebookChatJob.
	// This should almost always be used instead of []NotebookChatJob.
	NotebookChatJobSlice []*NotebookChatJob
	// NotebookChatJobHook is the signature for custom NotebookChatJob hook methods
	NotebookChatJobHook func(context.Context, boil.ContextExecutor, *NotebookChatJob) error

	notebookChatJobQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	notebookChatJobType                 = reflect.TypeOf(&NotebookChatJob{})
	notebookChatJobMapping              = queries.MakeStructMapping(notebookChatJobType)
	notebookChatJobPrimaryKeyMapping, _ = queries.BindMapping(notebookChatJobType, notebookChatJobMapping, notebookChatJobPrimaryKeyColumns)
	notebookChatJobInsertCacheMut       sync.RWMutex
	notebookChatJobInsertCache          = make(map[string]insertCache)
	notebookChatJobUpdateCacheMut       sync.RWMutex
	notebookChatJobUpdateCache          = make(map[string]updateCache)
	notebookChatJobUpsertCacheMut       sync.RWMutex
	notebookChatJobUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var notebookChatJobAfterSelectMu sync.Mutex
var notebookChatJobAfterSelectHooks []NotebookChatJobHook

var notebookChatJobBeforeInsertMu sync.Mutex
var notebookChatJobBeforeInsertHooks []NotebookChatJobHook
var notebookChatJobAfterInsertMu sync.Mutex
var notebookChatJobAfterInsertHooks []NotebookChatJobHook

var notebookChatJobBeforeUpdateMu sync.Mutex
var notebookChatJobBeforeUpdateHooks []NotebookChatJobHook
var notebookChatJobAfterUpdateMu sync.Mutex
var notebookChatJobAfterUpdateHooks []NotebookChatJobHook

var notebookChatJobBeforeDeleteMu sync.Mutex
var notebookChatJobBeforeDeleteHooks []NotebookChatJobHook
var notebookChatJobAfterDeleteMu sync.Mutex
var notebookChatJobAfterDeleteHooks []NotebookChatJobHook

var notebookChatJobBeforeUpsertMu sync.Mutex
var notebookChatJobBeforeUpsertHooks []NotebookChatJobHook
var notebookChatJobAfterUpsertMu sync.Mutex
var notebookChatJobAfterUpsertHooks []NotebookChatJobHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *NotebookChatJob) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookChatJobAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *NotebookChatJob) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookChatJobBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *NotebookChatJob) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookChatJobAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *NotebookChatJob) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookChatJobBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *NotebookChatJob) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookChatJobAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *NotebookChatJob) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookChatJobBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *NotebookChatJob) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookChatJobAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *NotebookChatJob) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookChatJobBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *NotebookChatJob) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookChatJobAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddNotebookChatJobHook registers your hook function for all future operations.
func AddNotebookChatJobHook(hookPoint boil.HookPoint, notebookChatJobHook NotebookChatJobHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		notebookChatJobAfterSelectMu.Lock()
		notebookChatJobAfterSelectHooks = append(notebookChatJobAfterSelectHooks, notebookChatJobHook)
		notebookChatJobAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		notebookChatJobBeforeInsertMu.Lock()
		notebookChatJobBeforeInsertHooks = append(notebookChatJobBeforeInsertHooks, notebookChatJobHook)
		notebookChatJobBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		notebookChatJobAfterInsertMu.Lock()
		notebookChatJobAfterInsertHooks = append(notebookChatJobAfterInsertHooks, notebookChatJobHook)
		notebookChatJobAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		notebookChatJobBeforeUpdateMu.Lock()
		notebookChatJobBeforeUpdateHooks = append(notebookChatJobBeforeUpdateHooks, notebookChatJobHook)
		notebookChatJobBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		notebookChatJobAfterUpdateMu.Lock()
		notebookChatJobAfterUpdateHooks = append(notebookChatJobAfterUpdateHooks, notebookChatJobHook)
		notebookChatJobAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		notebookChatJobBeforeDeleteMu.Lock()
		notebookChatJobBeforeDeleteHooks = append(notebookChatJobBeforeDeleteHooks, notebookChatJobHook)
		notebookChatJobBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		notebookChatJobAfterDeleteMu.Lock()
		notebookChatJobAfterDeleteHooks = append(notebookChatJobAfterDeleteHooks, notebookChatJobHook)
		notebookChatJobAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		notebookChatJobBeforeUpsertMu.Lock()
		notebookChatJobBeforeUpsertHooks = append(notebookChatJobBeforeUpsertHooks, notebookChatJobHook)
		notebookChatJobBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		notebookChatJobAfterUpsertMu.Lock()
		notebookChatJobAfterUpsertHooks = append(notebookChatJobAfterUpsertHooks, notebookChatJobHook)
		notebookChatJobAfterUpsertMu.Unlock()
	}
}

// One returns a single notebookChatJob record from the query.
func (q notebookChatJobQuery) One(ctx context.Context, exec boil.ContextExecutor) (*NotebookChatJob, error) {
	o := &NotebookChatJob{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for notebook_chat_jobs")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all NotebookChatJob records from the query.
func (q notebookChatJobQuery) All(ctx context.Context, exec boil.ContextExecutor) (NotebookChatJobSlice, error) {
	var o []*NotebookChatJob

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to NotebookChatJob slice")
	}

	if len(notebookChatJobAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all NotebookChatJob records in the query.
func (q notebookChatJobQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count notebook_chat_jobs rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q notebookChatJobQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if notebook_chat_jobs exists")
	}

	return count > 0, nil
}

// NotebookChatJobs retrieves all the records using an executor.
func NotebookChatJobs(mods ...qm.QueryMod) notebookChatJobQuery {
	mods = append(mods, qm.From("\"knowledge\".\"notebook_chat_jobs\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"knowledge\".\"notebook_chat_jobs\".*"})
	}

	return notebookChatJobQuery{q}
}

// FindNotebookChatJob retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindNotebookChatJob(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*NotebookChatJob, error) {
	notebookChatJobObj := &NotebookChatJob{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"knowledge\".\"notebook_chat_jobs\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, notebookChatJobObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from notebook_chat_jobs")
	}

	if err = notebookChatJobObj.doAfterSelectHooks(ctx, exec); err != nil {
		return notebookChatJobObj, err
	}

	return notebookChatJobObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *NotebookChatJob) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no notebook_chat_jobs provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(notebookChatJobColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	notebookChatJobInsertCacheMut.RLock()
	cache, cached := notebookChatJobInsertCache[key]
	notebookChatJobInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			notebookChatJobAllColumns,
			notebookChatJobColumnsWithDefault,
			notebookChatJobColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(notebookChatJobType, notebookChatJobMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(notebookChatJobType, notebookChatJobMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"knowledge\".\"notebook_chat_jobs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"knowledge\".\"notebook_chat_jobs\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into notebook_chat_jobs")
	}

	if !cached {
		notebookChatJobInsertCacheMut.Lock()
		notebookChatJobInsertCache[key] = cache
		notebookChatJobInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the NotebookChatJob.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *NotebookChatJob) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	notebookChatJobUpdateCacheMut.RLock()
	cache, cached := notebookChatJobUpdateCache[key]
	notebookChatJobUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			notebookChatJobAllColumns,
			notebookChatJobPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update notebook_chat_jobs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"knowledge\".\"notebook_chat_jobs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, notebookChatJobPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(notebookChatJobType, notebookChatJobMapping, append(wl, notebookChatJobPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update notebook_chat_jobs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for notebook_chat_jobs")
	}

	if !cached {
		notebookChatJobUpdateCacheMut.Lock()
		notebookChatJobUpdateCache[key] = cache
		notebookChatJobUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q notebookChatJobQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for notebook_chat_jobs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for notebook_chat_jobs")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o NotebookChatJobSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notebookChatJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"knowledge\".\"notebook_chat_jobs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, notebookChatJobPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in notebookChatJob slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all notebookChatJob")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *NotebookChatJob) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no notebook_chat_jobs provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(notebookChatJobColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	notebookChatJobUpsertCacheMut.RLock()
	cache, cached := notebookChatJobUpsertCache[key]
	notebookChatJobUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			notebookChatJobAllColumns,
			notebookChatJobColumnsWithDefault,
			notebookChatJobColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			notebookChatJobAllColumns,
			notebookChatJobPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert notebook_chat_jobs, could not build update column list")
		}

		ret := strmangle.SetComplement(notebookChatJobAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(notebookChatJobPrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert notebook_chat_jobs, could not build conflict column list")
			}

			conflict = make([]string, len(notebookChatJobPrimaryKeyColumns))
			copy(conflict, notebookChatJobPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"knowledge\".\"notebook_chat_jobs\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(notebookChatJobType, notebookChatJobMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(notebookChatJobType, notebookChatJobMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert notebook_chat_jobs")
	}

	if !cached {
		notebookChatJobUpsertCacheMut.Lock()
		notebookChatJobUpsertCache[key] = cache
		notebookChatJobUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single NotebookChatJob record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *NotebookChatJob) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no NotebookChatJob provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), notebookChatJobPrimaryKeyMapping)
	sql := "DELETE FROM \"knowledge\".\"notebook_chat_jobs\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from notebook_chat_jobs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for notebook_chat_jobs")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q notebookChatJobQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no notebookChatJobQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from notebook_chat_jobs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for notebook_chat_jobs")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o NotebookChatJobSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(notebookChatJobBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notebookChatJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"knowledge\".\"notebook_chat_jobs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, notebookChatJobPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from notebookChatJob slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for notebook_chat_jobs")
	}

	if len(notebookChatJobAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *NotebookChatJob) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindNotebookChatJob(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *NotebookChatJobSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := NotebookChatJobSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notebookChatJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"knowledge\".\"notebook_chat_jobs\".* FROM \"knowledge\".\"notebook_chat_jobs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, notebookChatJobPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in NotebookChatJobSlice")
	}

	*o = slice

	return nil
}

// NotebookChatJobExists checks if the NotebookChatJob row exists.
func NotebookChatJobExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"knowledge\".\"notebook_chat_jobs\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if notebook_chat_jobs exists")
	}

	return exists, nil
}

// Exists checks if the NotebookChatJob row exists.
func (o *NotebookChatJob) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return NotebookChatJobExists(ctx, exec, o.ID)
}
