// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// NotebookCampaign is an object representing the database table.
type NotebookCampaign struct {
	ID           string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	CampaignID   string    `boil:"campaign_id" json:"campaign_id" toml:"campaign_id" yaml:"campaign_id"`
	NotebookID   string    `boil:"notebook_id" json:"notebook_id" toml:"notebook_id" yaml:"notebook_id"`
	PeriodLabel  string    `boil:"period_label" json:"period_label" toml:"period_label" yaml:"period_label"`
	Status       string    `boil:"status" json:"status" toml:"status" yaml:"status"`
	SourceCount  int       `boil:"source_count" json:"source_count" toml:"source_count" yaml:"source_count"`
	LastSyncedAt null.Time `boil:"last_synced_at" json:"last_synced_at,omitempty" toml:"last_synced_at" yaml:"last_synced_at,omitempty"`
	CreatedAt    null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt    null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *notebookCampaignR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L notebookCampaignL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var NotebookCampaignColumns = struct {
	ID           string
	CampaignID   string
	NotebookID   string
	PeriodLabel  string
	Status       string
	SourceCount  string
	LastSyncedAt string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	CampaignID:   "campaign_id",
	NotebookID:   "notebook_id",
	PeriodLabel:  "period_label",
	Status:       "status",
	SourceCount:  "source_count",
	LastSyncedAt: "last_synced_at",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

var NotebookCampaignTableColumns = struct {
	ID           string
	CampaignID   string
	NotebookID   string
	PeriodLabel  string
	Status       string
	SourceCount  string
	LastSyncedAt string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "notebook_campaigns.id",
	CampaignID:   "notebook_campaigns.campaign_id",
	NotebookID:   "notebook_campaigns.notebook_id",
	PeriodLabel:  "notebook_campaigns.period_label",
	Status:       "notebook_campaigns.status",
	SourceCount:  "notebook_campaigns.source_count",
	LastSyncedAt: "notebook_campaigns.last_synced_at",
	CreatedAt:    "notebook_campaigns.created_at",
	UpdatedAt:    "notebook_campaigns.updated_at",
}

// Generated where

var NotebookCampaignWhere = struct {
	ID           whereHelperstring
	CampaignID   whereHelperstring
	NotebookID   whereHelperstring
	PeriodLabel  whereHelperstring
	Status       whereHelperstring
	SourceCount  whereHelperint
	LastSyncedAt whereHelpernull_Time
	CreatedAt    whereHelpernull_Time
	UpdatedAt    whereHelpernull_Time
}{
	ID:           whereHelperstring{field: "\"knowledge\".\"notebook_campaigns\".\"id\""},
	CampaignID:   whereHelperstring{field: "\"knowledge\".\"notebook_campaigns\".\"campaign_id\""},
	NotebookID:   whereHelperstring{field: "\"knowledge\".\"notebook_campaigns\".\"notebook_id\""},
	PeriodLabel:  whereHelperstring{field: "\"knowledge\".\"notebook_campaigns\".\"period_label\""},
	Status:       whereHelperstring{field: "\"knowledge\".\"notebook_campaigns\".\"status\""},
	SourceCount:  whereHelperint{field: "\"knowledge\".\"notebook_campaigns\".\"source_count\""},
	LastSyncedAt: whereHelpernull_Time{field: "\"knowledge\".\"notebook_campaigns\".\"last_synced_at\""},
	CreatedAt:    whereHelpernull_Time{field: "\"knowledge\".\"notebook_campaigns\".\"created_at\""},
	UpdatedAt:    whereHelpernull_Time{field: "\"knowledge\".\"notebook_campaigns\".\"updated_at\""},
}

// NotebookCampaignRels is where relationship names are stored.
var NotebookCampaignRels = struct {
}{}

// notebookCampaignR is where relationships are stored.
type notebookCampaignR struct {
}

// NewStruct creates a new relationship struct
func (*notebookCampaignR) NewStruct() *notebookCampaignR {
	return &notebookCampaignR{}
}

// notebookCampaignL is where Load methods for each relationship are stored.
type notebookCampaignL struct{}

var (
	notebookCampaignAllColumns            = []string{"id", "campaign_id", "notebook_id", "period_label", "status", "source_count", "last_synced_at", "created_at", "updated_at"}
	notebookCampaignColumnsWithoutDefault = []string{"campaign_id", "notebook_id", "period_label"}
	notebookCampaignColumnsWithDefault    = []string{"id", "status", "source_count", "last_synced_at", "created_at", "updated_at"}
	notebookCampaignPrimaryKeyColumns     = []string{"id"}
	notebookCampaignGeneratedColumns      = []string{}
)

type (
	// NotebookCampaignSlice is an alias for a slice of pointers to NotebookCampaign.
	// This should almost always be used instead of []NotebookCampaign.
	NotebookCampaignSlice []*NotebookCampaign
	// NotebookCampaignHook is the signature for custom NotebookCampaign hook methods
	NotebookCampaignHook func(context.Context, boil.ContextExecutor, *NotebookCampaign) error

	notebookCampaignQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	notebookCampaignType                 = reflect.TypeOf(&NotebookCampaign{})
	notebookCampaignMapping              = queries.MakeStructMapping(notebookCampaignType)
	notebookCampaignPrimaryKeyMapping, _ = queries.BindMapping(notebookCampaignType, notebookCampaignMapping, notebookCampaignPrimaryKeyColumns)
	notebookCampaignInsertCacheMut       sync.RWMutex
	notebookCampaignInsertCache          = make(map[string]insertCache)
	notebookCampaignUpdateCacheMut       sync.RWMutex
	notebookCampaignUpdateCache          = make(map[string]updateCache)
	notebookCampaignUpsertCacheMut       sync.RWMutex
	notebookCampaignUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var notebookCampaignAfterSelectMu sync.Mutex
var notebookCampaignAfterSelectHooks []NotebookCampaignHook

var notebookCampaignBeforeInsertMu sync.Mutex
var notebookCampaignBeforeInsertHooks []NotebookCampaignHook
var notebookCampaignAfterInsertMu sync.Mutex
var notebookCampaignAfterInsertHooks []NotebookCampaignHook

var notebookCampaignBeforeUpdateMu sync.Mutex
var notebookCampaignBeforeUpdateHooks []NotebookCampaignHook
var notebookCampaignAfterUpdateMu sync.Mutex
var notebookCampaignAfterUpdateHooks []NotebookCampaignHook

var notebookCampaignBeforeDeleteMu sync.Mutex
var notebookCampaignBeforeDeleteHooks []NotebookCampaignHook
var notebookCampaignAfterDeleteMu sync.Mutex
var notebookCampaignAfterDeleteHooks []NotebookCampaignHook

var notebookCampaignBeforeUpsertMu sync.Mutex
var notebookCampaignBeforeUpsertHooks []NotebookCampaignHook
var notebookCampaignAfterUpsertMu sync.Mutex
var notebookCampaignAfterUpsertHooks []NotebookCampaignHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *NotebookCampaign) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookCampaignAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *NotebookCampaign) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookCampaignBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *NotebookCampaign) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookCampaignAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *NotebookCampaign) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookCampaignBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *NotebookCampaign) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookCampaignAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *NotebookCampaign) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookCampaignBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *NotebookCampaign) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookCampaignAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *NotebookCampaign) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookCampaignBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *NotebookCampaign) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookCampaignAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddNotebookCampaignHook registers your hook function for all future operations.
func AddNotebookCampaignHook(hookPoint boil.HookPoint, notebookCampaignHook NotebookCampaignHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		notebookCampaignAfterSelectMu.Lock()
		notebookCampaignAfterSelectHooks = append(notebookCampaignAfterSelectHooks, notebookCampaignHook)
		notebookCampaignAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		notebookCampaignBeforeInsertMu.Lock()
		notebookCampaignBeforeInsertHooks = append(notebookCampaignBeforeInsertHooks, notebookCampaignHook)
		notebookCampaignBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		notebookCampaignAfterInsertMu.Lock()
		notebookCampaignAfterInsertHooks = append(notebookCampaignAfterInsertHooks, notebookCampaignHook)
		notebookCampaignAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		notebookCampaignBeforeUpdateMu.Lock()
		notebookCampaignBeforeUpdateHooks = append(notebookCampaignBeforeUpdateHooks, notebookCampaignHook)
		notebookCampaignBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		notebookCampaignAfterUpdateMu.Lock()
		notebookCampaignAfterUpdateHooks = append(notebookCampaignAfterUpdateHooks, notebookCampaignHook)
		notebookCampaignAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		notebookCampaignBeforeDeleteMu.Lock()
		notebookCampaignBeforeDeleteHooks = append(notebookCampaignBeforeDeleteHooks, notebookCampaignHook)
		notebookCampaignBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		notebookCampaignAfterDeleteMu.Lock()
		notebookCampaignAfterDeleteHooks = append(notebookCampaignAfterDeleteHooks, notebookCampaignHook)
		notebookCampaignAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		notebookCampaignBeforeUpsertMu.Lock()
		notebookCampaignBeforeUpsertHooks = append(notebookCampaignBeforeUpsertHooks, notebookCampaignHook)
		notebookCampaignBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		notebookCampaignAfterUpsertMu.Lock()
		notebookCampaignAfterUpsertHooks = append(notebookCampaignAfterUpsertHooks, notebookCampaignHook)
		notebookCampaignAfterUpsertMu.Unlock()
	}
}

// One returns a single notebookCampaign record from the query.
func (q notebookCampaignQuery) One(ctx context.Context, exec boil.ContextExecutor) (*NotebookCampaign, error) {
	o := &NotebookCampaign{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for notebook_campaigns")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all NotebookCampaign records from the query.
func (q notebookCampaignQuery) All(ctx context.Context, exec boil.ContextExecutor) (NotebookCampaignSlice, error) {
	var o []*NotebookCampaign

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to NotebookCampaign slice")
	}

	if len(notebookCampaignAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all NotebookCampaign records in the query.
func (q notebookCampaignQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count notebook_campaigns rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q notebookCampaignQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if notebook_campaigns exists")
	}

	return count > 0, nil
}

// NotebookCampaigns retrieves all the records using an executor.
func NotebookCampaigns(mods ...qm.QueryMod) notebookCampaignQuery {
	mods = append(mods, qm.From("\"knowledge\".\"notebook_campaigns\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"knowledge\".\"notebook_campaigns\".*"})
	}

	return notebookCampaignQuery{q}
}

// FindNotebookCampaign retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindNotebookCampaign(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*NotebookCampaign, error) {
	notebookCampaignObj := &NotebookCampaign{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"knowledge\".\"notebook_campaigns\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, notebookCampaignObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from notebook_campaigns")
	}

	if err = notebookCampaignObj.doAfterSelectHooks(ctx, exec); err != nil {
		return notebookCampaignObj, err
	}

	return notebookCampaignObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *NotebookCampaign) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no notebook_campaigns provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(notebookCampaignColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	notebookCampaignInsertCacheMut.RLock()
	cache, cached := notebookCampaignInsertCache[key]
	notebookCampaignInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			notebookCampaignAllColumns,
			notebookCampaignColumnsWithDefault,
			notebookCampaignColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(notebookCampaignType, notebookCampaignMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(notebookCampaignType, notebookCampaignMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"knowledge\".\"notebook_campaigns\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"knowledge\".\"notebook_campaigns\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into notebook_campaigns")
	}

	if !cached {
		notebookCampaignInsertCacheMut.Lock()
		notebookCampaignInsertCache[key] = cache
		notebookCampaignInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the NotebookCampaign.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *NotebookCampaign) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	notebookCampaignUpdateCacheMut.RLock()
	cache, cached := notebookCampaignUpdateCache[key]
	notebookCampaignUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			notebookCampaignAllColumns,
			notebookCampaignPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update notebook_campaigns, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"knowledge\".\"notebook_campaigns\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, notebookCampaignPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(notebookCampaignType, notebookCampaignMapping, append(wl, notebookCampaignPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update notebook_campaigns row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for notebook_campaigns")
	}

	if !cached {
		notebookCampaignUpdateCacheMut.Lock()
		notebookCampaignUpdateCache[key] = cache
		notebookCampaignUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q notebookCampaignQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for notebook_campaigns")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for notebook_campaigns")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o NotebookCampaignSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notebookCampaignPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"knowledge\".\"notebook_campaigns\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, notebookCampaignPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in notebookCampaign slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all notebookCampaign")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *NotebookCampaign) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no notebook_campaigns provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(notebookCampaignColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	notebookCampaignUpsertCacheMut.RLock()
	cache, cached := notebookCampaignUpsertCache[key]
	notebookCampaignUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			notebookCampaignAllColumns,
			notebookCampaignColumnsWithDefault,
			notebookCampaignColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			notebookCampaignAllColumns,
			notebookCampaignPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert notebook_campaigns, could not build update column list")
		}

		ret := strmangle.SetComplement(notebookCampaignAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(notebookCampaignPrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert notebook_campaigns, could not build conflict column list")
			}

			conflict = make([]string, len(notebookCampaignPrimaryKeyColumns))
			copy(conflict, notebookCampaignPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"knowledge\".\"notebook_campaigns\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(notebookCampaignType, notebookCampaignMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(notebookCampaignType, notebookCampaignMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert notebook_campaigns")
	}

	if !cached {
		notebookCampaignUpsertCacheMut.Lock()
		notebookCampaignUpsertCache[key] = cache
		notebookCampaignUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single NotebookCampaign record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *NotebookCampaign) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no NotebookCampaign provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), notebookCampaignPrimaryKeyMapping)
	sql := "DELETE FROM \"knowledge\".\"notebook_campaigns\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from notebook_campaigns")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for notebook_campaigns")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q notebookCampaignQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no notebookCampaignQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from notebook_campaigns")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for notebook_campaigns")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o NotebookCampaignSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(notebookCampaignBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notebookCampaignPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"knowledge\".\"notebook_campaigns\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, notebookCampaignPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from notebookCampaign slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for notebook_campaigns")
	}

	if len(notebookCampaignAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *NotebookCampaign) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindNotebookCampaign(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *NotebookCampaignSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := NotebookCampaignSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notebookCampaignPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"knowledge\".\"notebook_campaigns\".* FROM \"knowledge\".\"notebook_campaigns\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, notebookCampaignPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in NotebookCampaignSlice")
	}

	*o = slice

	return nil
}

// NotebookCampaignExists checks if the NotebookCampaign row exists.
func NotebookCampaignExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"knowledge\".\"notebook_campaigns\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if notebook_campaigns exists")
	}

	return exists, nil
}

// Exists checks if the NotebookCampaign row exists.
func (o *NotebookCampaign) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return NotebookCampaignExists(ctx, exec, o.ID)
}
