// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// NotebookSource is an object representing the database table.
type NotebookSource struct {
	ID         string `boil:"id" json:"id" toml:"id" yaml:"id"`
	CampaignID string `boil:"campaign_id" json:"campaign_id" toml:"campaign_id" yaml:"campaign_id"`
	NotebookID string `boil:"notebook_id" json:"notebook_id" toml:"notebook_id" yaml:"notebook_id"`
	WeekLabel  string `boil:"week_label" json:"week_label" toml:"week_label" yaml:"week_label"`
	PartNumber int    `boil:"part_number" json:"part_number" toml:"part_number" yaml:"part_number"`
	Title      string `boil:"title" json:"title" toml:"title" yaml:"title"`
	PostCount  int    `boil:"post_count" json:"post_count" toml:"post_count" yaml:"post_count"`
	// SHA256 hash of markdown content for deduplication - skip re-upload if hash matches
	ContentHash  null.String `boil:"content_hash" json:"content_hash,omitempty" toml:"content_hash" yaml:"content_hash,omitempty"`
	MaestroJobID null.String `boil:"maestro_job_id" json:"maestro_job_id,omitempty" toml:"maestro_job_id" yaml:"maestro_job_id,omitempty"`
	// PENDING: Not yet uploaded, UPLOADING: Maestro job in progress, SYNCED: Successfully uploaded, FAILED: Upload failed
	Status       string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	RetryCount   int         `boil:"retry_count" json:"retry_count" toml:"retry_count" yaml:"retry_count"`
	ErrorMessage null.String `boil:"error_message" json:"error_message,omitempty" toml:"error_message" yaml:"error_message,omitempty"`
	SyncedAt     null.Time   `boil:"synced_at" json:"synced_at,omitempty" toml:"synced_at" yaml:"synced_at,omitempty"`
	CreatedAt    null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`

	R *notebookSourceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L notebookSourceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var NotebookSourceColumns = struct {
	ID           string
	CampaignID   string
	NotebookID   string
	WeekLabel    string
	PartNumber   string
	Title        string
	PostCount    string
	ContentHash  string
	MaestroJobID string
	Status       string
	RetryCount   string
	ErrorMessage string
	SyncedAt     string
	CreatedAt    string
}{
	ID:           "id",
	CampaignID:   "campaign_id",
	NotebookID:   "notebook_id",
	WeekLabel:    "week_label",
	PartNumber:   "part_number",
	Title:        "title",
	PostCount:    "post_count",
	ContentHash:  "content_hash",
	MaestroJobID: "maestro_job_id",
	Status:       "status",
	RetryCount:   "retry_count",
	ErrorMessage: "error_message",
	SyncedAt:     "synced_at",
	CreatedAt:    "created_at",
}

var NotebookSourceTableColumns = struct {
	ID           string
	CampaignID   string
	NotebookID   string
	WeekLabel    string
	PartNumber   string
	Title        string
	PostCount    string
	ContentHash  string
	MaestroJobID string
	Status       string
	RetryCount   string
	ErrorMessage string
	SyncedAt     string
	CreatedAt    string
}{
	ID:           "notebook_sources.id",
	CampaignID:   "notebook_sources.campaign_id",
	NotebookID:   "notebook_sources.notebook_id",
	WeekLabel:    "notebook_sources.week_label",
	PartNumber:   "notebook_sources.part_number",
	Title:        "notebook_sources.title",
	PostCount:    "notebook_sources.post_count",
	ContentHash:  "notebook_sources.content_hash",
	MaestroJobID: "notebook_sources.maestro_job_id",
	Status:       "notebook_sources.status",
	RetryCount:   "notebook_sources.retry_count",
	ErrorMessage: "notebook_sources.error_message",
	SyncedAt:     "notebook_sources.synced_at",
	CreatedAt:    "notebook_sources.created_at",
}

// Generated where

var NotebookSourceWhere = struct {
	ID           whereHelperstring
	CampaignID   whereHelperstring
	NotebookID   whereHelperstring
	WeekLabel    whereHelperstring
	PartNumber   whereHelperint
	Title        whereHelperstring
	PostCount    whereHelperint
	ContentHash  whereHelpernull_String
	MaestroJobID whereHelpernull_String
	Status       whereHelperstring
	RetryCount   whereHelperint
	ErrorMessage whereHelpernull_String
	SyncedAt     whereHelpernull_Time
	CreatedAt    whereHelpernull_Time
}{
	ID:           whereHelperstring{field: "\"knowledge\".\"notebook_sources\".\"id\""},
	CampaignID:   whereHelperstring{field: "\"knowledge\".\"notebook_sources\".\"campaign_id\""},
	NotebookID:   whereHelperstring{field: "\"knowledge\".\"notebook_sources\".\"notebook_id\""},
	WeekLabel:    whereHelperstring{field: "\"knowledge\".\"notebook_sources\".\"week_label\""},
	PartNumber:   whereHelperint{field: "\"knowledge\".\"notebook_sources\".\"part_number\""},
	Title:        whereHelperstring{field: "\"knowledge\".\"notebook_sources\".\"title\""},
	PostCount:    whereHelperint{field: "\"knowledge\".\"notebook_sources\".\"post_count\""},
	ContentHash:  whereHelpernull_String{field: "\"knowledge\".\"notebook_sources\".\"content_hash\""},
	MaestroJobID: whereHelpernull_String{field: "\"knowledge\".\"notebook_sources\".\"maestro_job_id\""},
	Status:       whereHelperstring{field: "\"knowledge\".\"notebook_sources\".\"status\""},
	RetryCount:   whereHelperint{field: "\"knowledge\".\"notebook_sources\".\"retry_count\""},
	ErrorMessage: whereHelpernull_String{field: "\"knowledge\".\"notebook_sources\".\"error_message\""},
	SyncedAt:     whereHelpernull_Time{field: "\"knowledge\".\"notebook_sources\".\"synced_at\""},
	CreatedAt:    whereHelpernull_Time{field: "\"knowledge\".\"notebook_sources\".\"created_at\""},
}

// NotebookSourceRels is where relationship names are stored.
var NotebookSourceRels = struct {
}{}

// notebookSourceR is where relationships are stored.
type notebookSourceR struct {
}

// NewStruct creates a new relationship struct
func (*notebookSourceR) NewStruct() *notebookSourceR {
	return &notebookSourceR{}
}

// notebookSourceL is where Load methods for each relationship are stored.
type notebookSourceL struct{}

var (
	notebookSourceAllColumns            = []string{"id", "campaign_id", "notebook_id", "week_label", "part_number", "title", "post_count", "content_hash", "maestro_job_id", "status", "retry_count", "error_message", "synced_at", "created_at"}
	notebookSourceColumnsWithoutDefault = []string{"campaign_id", "notebook_id", "week_label", "title"}
	notebookSourceColumnsWithDefault    = []string{"id", "part_number", "post_count", "content_hash", "maestro_job_id", "status", "retry_count", "error_message", "synced_at", "created_at"}
	notebookSourcePrimaryKeyColumns     = []string{"id"}
	notebookSourceGeneratedColumns      = []string{}
)

type (
	// NotebookSourceSlice is an alias for a slice of pointers to NotebookSource.
	// This should almost always be used instead of []NotebookSource.
	NotebookSourceSlice []*NotebookSource
	// NotebookSourceHook is the signature for custom NotebookSource hook methods
	NotebookSourceHook func(context.Context, boil.ContextExecutor, *NotebookSource) error

	notebookSourceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	notebookSourceType                 = reflect.TypeOf(&NotebookSource{})
	notebookSourceMapping              = queries.MakeStructMapping(notebookSourceType)
	notebookSourcePrimaryKeyMapping, _ = queries.BindMapping(notebookSourceType, notebookSourceMapping, notebookSourcePrimaryKeyColumns)
	notebookSourceInsertCacheMut       sync.RWMutex
	notebookSourceInsertCache          = make(map[string]insertCache)
	notebookSourceUpdateCacheMut       sync.RWMutex
	notebookSourceUpdateCache          = make(map[string]updateCache)
	notebookSourceUpsertCacheMut       sync.RWMutex
	notebookSourceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var notebookSourceAfterSelectMu sync.Mutex
var notebookSourceAfterSelectHooks []NotebookSourceHook

var notebookSourceBeforeInsertMu sync.Mutex
var notebookSourceBeforeInsertHooks []NotebookSourceHook
var notebookSourceAfterInsertMu sync.Mutex
var notebookSourceAfterInsertHooks []NotebookSourceHook

var notebookSourceBeforeUpdateMu sync.Mutex
var notebookSourceBeforeUpdateHooks []NotebookSourceHook
var notebookSourceAfterUpdateMu sync.Mutex
var notebookSourceAfterUpdateHooks []NotebookSourceHook

var notebookSourceBeforeDeleteMu sync.Mutex
var notebookSourceBeforeDeleteHooks []NotebookSourceHook
var notebookSourceAfterDeleteMu sync.Mutex
var notebookSourceAfterDeleteHooks []NotebookSourceHook

var notebookSourceBeforeUpsertMu sync.Mutex
var notebookSourceBeforeUpsertHooks []NotebookSourceHook
var notebookSourceAfterUpsertMu sync.Mutex
var notebookSourceAfterUpsertHooks []NotebookSourceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *NotebookSource) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookSourceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *NotebookSource) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookSourceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *NotebookSource) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookSourceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *NotebookSource) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookSourceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *NotebookSource) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookSourceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *NotebookSource) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookSourceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *NotebookSource) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookSourceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *NotebookSource) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookSourceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *NotebookSource) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range notebookSourceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddNotebookSourceHook registers your hook function for all future operations.
func AddNotebookSourceHook(hookPoint boil.HookPoint, notebookSourceHook NotebookSourceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		notebookSourceAfterSelectMu.Lock()
		notebookSourceAfterSelectHooks = append(notebookSourceAfterSelectHooks, notebookSourceHook)
		notebookSourceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		notebookSourceBeforeInsertMu.Lock()
		notebookSourceBeforeInsertHooks = append(notebookSourceBeforeInsertHooks, notebookSourceHook)
		notebookSourceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		notebookSourceAfterInsertMu.Lock()
		notebookSourceAfterInsertHooks = append(notebookSourceAfterInsertHooks, notebookSourceHook)
		notebookSourceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		notebookSourceBeforeUpdateMu.Lock()
		notebookSourceBeforeUpdateHooks = append(notebookSourceBeforeUpdateHooks, notebookSourceHook)
		notebookSourceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		notebookSourceAfterUpdateMu.Lock()
		notebookSourceAfterUpdateHooks = append(notebookSourceAfterUpdateHooks, notebookSourceHook)
		notebookSourceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		notebookSourceBeforeDeleteMu.Lock()
		notebookSourceBeforeDeleteHooks = append(notebookSourceBeforeDeleteHooks, notebookSourceHook)
		notebookSourceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		notebookSourceAfterDeleteMu.Lock()
		notebookSourceAfterDeleteHooks = append(notebookSourceAfterDeleteHooks, notebookSourceHook)
		notebookSourceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		notebookSourceBeforeUpsertMu.Lock()
		notebookSourceBeforeUpsertHooks = append(notebookSourceBeforeUpsertHooks, notebookSourceHook)
		notebookSourceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		notebookSourceAfterUpsertMu.Lock()
		notebookSourceAfterUpsertHooks = append(notebookSourceAfterUpsertHooks, notebookSourceHook)
		notebookSourceAfterUpsertMu.Unlock()
	}
}

// One returns a single notebookSource record from the query.
func (q notebookSourceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*NotebookSource, error) {
	o := &NotebookSource{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for notebook_sources")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all NotebookSource records from the query.
func (q notebookSourceQuery) All(ctx context.Context, exec boil.ContextExecutor) (NotebookSourceSlice, error) {
	var o []*NotebookSource

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to NotebookSource slice")
	}

	if len(notebookSourceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all NotebookSource records in the query.
func (q notebookSourceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count notebook_sources rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q notebookSourceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if notebook_sources exists")
	}

	return count > 0, nil
}

// NotebookSources retrieves all the records using an executor.
func NotebookSources(mods ...qm.QueryMod) notebookSourceQuery {
	mods = append(mods, qm.From("\"knowledge\".\"notebook_sources\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"knowledge\".\"notebook_sources\".*"})
	}

	return notebookSourceQuery{q}
}

// FindNotebookSource retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindNotebookSource(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*NotebookSource, error) {
	notebookSourceObj := &NotebookSource{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"knowledge\".\"notebook_sources\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, notebookSourceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from notebook_sources")
	}

	if err = notebookSourceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return notebookSourceObj, err
	}

	return notebookSourceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *NotebookSource) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no notebook_sources provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(notebookSourceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	notebookSourceInsertCacheMut.RLock()
	cache, cached := notebookSourceInsertCache[key]
	notebookSourceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			notebookSourceAllColumns,
			notebookSourceColumnsWithDefault,
			notebookSourceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(notebookSourceType, notebookSourceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(notebookSourceType, notebookSourceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"knowledge\".\"notebook_sources\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"knowledge\".\"notebook_sources\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into notebook_sources")
	}

	if !cached {
		notebookSourceInsertCacheMut.Lock()
		notebookSourceInsertCache[key] = cache
		notebookSourceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the NotebookSource.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *NotebookSource) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	notebookSourceUpdateCacheMut.RLock()
	cache, cached := notebookSourceUpdateCache[key]
	notebookSourceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			notebookSourceAllColumns,
			notebookSourcePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update notebook_sources, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"knowledge\".\"notebook_sources\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, notebookSourcePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(notebookSourceType, notebookSourceMapping, append(wl, notebookSourcePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update notebook_sources row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for notebook_sources")
	}

	if !cached {
		notebookSourceUpdateCacheMut.Lock()
		notebookSourceUpdateCache[key] = cache
		notebookSourceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q notebookSourceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for notebook_sources")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for notebook_sources")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o NotebookSourceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notebookSourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"knowledge\".\"notebook_sources\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, notebookSourcePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in notebookSource slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all notebookSource")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *NotebookSource) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("sqlboiler: no notebook_sources provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(notebookSourceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	notebookSourceUpsertCacheMut.RLock()
	cache, cached := notebookSourceUpsertCache[key]
	notebookSourceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			notebookSourceAllColumns,
			notebookSourceColumnsWithDefault,
			notebookSourceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			notebookSourceAllColumns,
			notebookSourcePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert notebook_sources, could not build update column list")
		}

		ret := strmangle.SetComplement(notebookSourceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(notebookSourcePrimaryKeyColumns) == 0 {
				return errors.New("sqlboiler: unable to upsert notebook_sources, could not build conflict column list")
			}

			conflict = make([]string, len(notebookSourcePrimaryKeyColumns))
			copy(conflict, notebookSourcePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"knowledge\".\"notebook_sources\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(notebookSourceType, notebookSourceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(notebookSourceType, notebookSourceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert notebook_sources")
	}

	if !cached {
		notebookSourceUpsertCacheMut.Lock()
		notebookSourceUpsertCache[key] = cache
		notebookSourceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single NotebookSource record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *NotebookSource) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no NotebookSource provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), notebookSourcePrimaryKeyMapping)
	sql := "DELETE FROM \"knowledge\".\"notebook_sources\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from notebook_sources")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for notebook_sources")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q notebookSourceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no notebookSourceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from notebook_sources")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for notebook_sources")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o NotebookSourceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(notebookSourceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notebookSourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"knowledge\".\"notebook_sources\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, notebookSourcePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from notebookSource slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for notebook_sources")
	}

	if len(notebookSourceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *NotebookSource) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindNotebookSource(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *NotebookSourceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := NotebookSourceSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notebookSourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"knowledge\".\"notebook_sources\".* FROM \"knowledge\".\"notebook_sources\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, notebookSourcePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in NotebookSourceSlice")
	}

	*o = slice

	return nil
}

// NotebookSourceExists checks if the NotebookSource row exists.
func NotebookSourceExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"knowledge\".\"notebook_sources\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if notebook_sources exists")
	}

	return exists, nil
}

// Exists checks if the NotebookSource row exists.
func (o *NotebookSource) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return NotebookSourceExists(ctx, exec, o.ID)
}
