package notebook

// NotebookInfo represents metadata about a notebook.
type NotebookInfo struct {
	ID          string // Unique identifier for the notebook
	CampaignID  string // Associated campaign ID
	PeriodLabel string // Time period label (e.g., "2026-W12")
	CreatedAt   string // Timestamp of notebook creation
}

// SyncPartInput represents the input for syncing parts to a notebook.
type SyncPartInput struct {
	CampaignID string         // Associated campaign ID
	Parts      []MarkdownPart // List of markdown parts to sync
}

// MarkdownPart represents a section of content to be synced to a notebook.
type MarkdownPart struct {
	Title       string // Title of the part (e.g., "SMAP | Campaign X | 2026-W12 | Part 1")
	Content     string // Content of the part
	WeekLabel   string // ISO week label (e.g., "2026-W12")
	PartNum     int    // Part number within the week
	PostCount   int    // Number of posts in this part
	ContentHash string // SHA256 hash of the content for deduplication
}

// WebhookPayload represents the payload received from Maestro webhook callbacks.
type WebhookPayload struct {
	Action string                 // Action type (e.g., "upload_sources", "create_notebook")
	Data   map[string]interface{} // Additional data related to the action
}

// RetryOutput represents the result of retrying failed jobs.
type RetryOutput struct {
	RetriedJobs int // Number of jobs retried
	FailedJobs  int // Number of jobs that still failed
}

// ChatJob represents a job for asynchronous chat processing.
type ChatJob struct {
	ID             string  // Unique identifier for the job
	ConversationID string  // Associated conversation ID
	CampaignID     string  // Associated campaign ID
	UserMessage    string  // The user's message
	MaestroJobID   string  // ID of the job in Maestro
	Status         string  // Current status of the job (e.g., PENDING, PROCESSING, COMPLETED)
	NotebookAnswer string  // The answer generated by the notebook
	FallbackUsed   bool    // Whether a fallback mechanism was used
	CreatedAt      string  // Timestamp when the job was created
	CompletedAt    *string // Timestamp when the job was completed (optional)
	ExpiresAt      string  // Timestamp when the job expires
}
